
services:
  wallet-app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - config.env  
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - wallet-network

  db:
    image: postgres:15-alpine
    env_file:
      - config.env  # Те же переменные для БД
    environment:
      POSTGRES_USER: ${DB_USER:-user}  # Значение по умолчанию
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-walletdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-walletdb}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - wallet-network
    ports:
      - "5432:5432"  

networks:
  wallet-network:
    driver: bridge

volumes:
  postgres_data: